# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: filetransfer.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x66iletransfer.proto\x12\x0c\x66iletransfer\"*\n\tFileChunk\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\"\x17\n\x07Request\x12\x0c\n\x04name\x18\x01 \x01(\t\"!\n\x0eUploadResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x93\x01\n\x0c\x46ileTransfer\x12\x43\n\nUploadFile\x12\x17.filetransfer.FileChunk\x1a\x1c.filetransfer.UploadResponse\x12>\n\x0c\x44ownloadFile\x12\x15.filetransfer.Request\x1a\x17.filetransfer.FileChunkb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'filetransfer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FILECHUNK']._serialized_start=36
  _globals['_FILECHUNK']._serialized_end=78
  _globals['_REQUEST']._serialized_start=80
  _globals['_REQUEST']._serialized_end=103
  _globals['_UPLOADRESPONSE']._serialized_start=105
  _globals['_UPLOADRESPONSE']._serialized_end=138
  _globals['_FILETRANSFER']._serialized_start=141
  _globals['_FILETRANSFER']._serialized_end=288
# @@protoc_insertion_point(module_scope)
