# Usa la imagen base de Python
FROM python:3.9

# Establece el directorio de trabajo en /app
WORKDIR /app

# Copia el archivo de requerimientos al contenedor
COPY requirements.txt .

# Instala las dependencias
RUN pip install -r requirements.txt

# Copia todo el contenido del directorio actual al directorio /app en el contenedor
COPY . .

# Expone el puerto 8000 para la aplicación FastAPI
EXPOSE 8000

# Ejecuta la aplicación FastAPI cuando el contenedor se inicie
CMD ["uvicorn", "Main:app", "--host", "0.0.0.0", "--port", "8000"]
